#!/bin/sh

VBoxHeadless -startvm new-1-1-1 &
VBoxHeadless -startvm new-2-1-1 &
VBoxHeadless -startvm new-3-1-1 &
VBoxHeadless -startvm new-4-1-1 &
VBoxHeadless -startvm new-5-1-1 &
VBoxHeadless -startvm new-1-1-2 &
VBoxHeadless -startvm new-2-1-2 &
VBoxHeadless -startvm new-3-1-2 &
VBoxHeadless -startvm new-4-1-2 &
VBoxHeadless -startvm new-5-1-2 &
VBoxHeadless -startvm new-1-2-1 &
VBoxHeadless -startvm new-2-2-1 &
VBoxHeadless -startvm new-3-2-1 &
VBoxHeadless -startvm new-4-2-1 &
VBoxHeadless -startvm new-5-2-1 &
VBoxHeadless -startvm new-1-2-2 &
VBoxHeadless -startvm new-2-2-2 &
VBoxHeadless -startvm new-3-2-2 &
VBoxHeadless -startvm new-4-2-2 &
VBoxHeadless -startvm new-5-2-2 &
VBoxHeadless -startvm new-1-3-1 &
VBoxHeadless -startvm new-2-3-1 &
VBoxHeadless -startvm new-3-3-1 &
VBoxHeadless -startvm new-4-3-1 &
VBoxHeadless -startvm new-5-3-1 &
VBoxHeadless -startvm new-1-3-2 &
VBoxHeadless -startvm new-2-3-2 &
VBoxHeadless -startvm new-3-3-2 &
VBoxHeadless -startvm new-4-3-2 &
VBoxHeadless -startvm new-5-3-2 &
VBoxHeadless -startvm new-1-4-1 &
VBoxHeadless -startvm new-2-4-1 &
VBoxHeadless -startvm new-3-4-1 &
VBoxHeadless -startvm new-4-4-1 &
VBoxHeadless -startvm new-5-4-1 &
VBoxHeadless -startvm new-1-4-2 &
VBoxHeadless -startvm new-2-4-2 &
VBoxHeadless -startvm new-3-4-2 &
VBoxHeadless -startvm new-4-4-2 &
VBoxHeadless -startvm new-5-4-2 &

