#!/bin/sh

VBoxHeadless -startvm old-1-1-1 &
VBoxHeadless -startvm old-2-1-1 &
VBoxHeadless -startvm old-3-1-1 &
VBoxHeadless -startvm old-4-1-1 &
VBoxHeadless -startvm old-5-1-1 &
VBoxHeadless -startvm old-1-1-2 &
VBoxHeadless -startvm old-2-1-2 &
VBoxHeadless -startvm old-3-1-2 &
VBoxHeadless -startvm old-4-1-2 &
VBoxHeadless -startvm old-5-1-2 &
VBoxHeadless -startvm old-1-2-1 &
VBoxHeadless -startvm old-2-2-1 &
VBoxHeadless -startvm old-3-2-1 &
VBoxHeadless -startvm old-4-2-1 &
VBoxHeadless -startvm old-5-2-1 &
VBoxHeadless -startvm old-1-2-2 &
VBoxHeadless -startvm old-2-2-2 &
VBoxHeadless -startvm old-3-2-2 &
VBoxHeadless -startvm old-4-2-2 &
VBoxHeadless -startvm old-5-2-2 &
VBoxHeadless -startvm old-1-3-1 &
VBoxHeadless -startvm old-2-3-1 &
VBoxHeadless -startvm old-3-3-1 &
VBoxHeadless -startvm old-4-3-1 &
VBoxHeadless -startvm old-5-3-1 &
VBoxHeadless -startvm old-1-3-2 &
VBoxHeadless -startvm old-2-3-2 &
VBoxHeadless -startvm old-3-3-2 &
VBoxHeadless -startvm old-4-3-2 &
VBoxHeadless -startvm old-5-3-2 &
VBoxHeadless -startvm old-1-4-1 &
VBoxHeadless -startvm old-2-4-1 &
VBoxHeadless -startvm old-3-4-1 &
VBoxHeadless -startvm old-4-4-1 &
VBoxHeadless -startvm old-5-4-1 &
VBoxHeadless -startvm old-1-4-2 &
VBoxHeadless -startvm old-2-4-2 &
VBoxHeadless -startvm old-3-4-2 &
VBoxHeadless -startvm old-4-4-2 &
VBoxHeadless -startvm old-5-4-2 &
