#!/bin/sh

VBoxManage controlvm new-1-1-1 poweroff soft
VBoxManage controlvm new-2-1-1 poweroff soft
VBoxManage controlvm new-3-1-1 poweroff soft
VBoxManage controlvm new-4-1-1 poweroff soft
VBoxManage controlvm new-5-1-1 poweroff soft
VBoxManage controlvm new-1-1-2 poweroff soft
VBoxManage controlvm new-2-1-2 poweroff soft
VBoxManage controlvm new-3-1-2 poweroff soft
VBoxManage controlvm new-4-1-2 poweroff soft
VBoxManage controlvm new-5-1-2 poweroff soft
VBoxManage controlvm new-1-2-1 poweroff soft
VBoxManage controlvm new-2-2-1 poweroff soft
VBoxManage controlvm new-3-2-1 poweroff soft
VBoxManage controlvm new-4-2-1 poweroff soft
VBoxManage controlvm new-5-2-1 poweroff soft
VBoxManage controlvm new-1-2-2 poweroff soft
VBoxManage controlvm new-2-2-2 poweroff soft
VBoxManage controlvm new-3-2-2 poweroff soft
VBoxManage controlvm new-4-2-2 poweroff soft
VBoxManage controlvm new-5-2-2 poweroff soft
VBoxManage controlvm new-1-3-1 poweroff soft
VBoxManage controlvm new-2-3-1 poweroff soft
VBoxManage controlvm new-3-3-1 poweroff soft
VBoxManage controlvm new-4-3-1 poweroff soft
VBoxManage controlvm new-5-3-1 poweroff soft
VBoxManage controlvm new-1-3-2 poweroff soft
VBoxManage controlvm new-2-3-2 poweroff soft
VBoxManage controlvm new-3-3-2 poweroff soft
VBoxManage controlvm new-4-3-2 poweroff soft
VBoxManage controlvm new-5-3-2 poweroff soft
VBoxManage controlvm new-1-4-1 poweroff soft
VBoxManage controlvm new-2-4-1 poweroff soft
VBoxManage controlvm new-3-4-1 poweroff soft
VBoxManage controlvm new-4-4-1 poweroff soft
VBoxManage controlvm new-5-4-1 poweroff soft
VBoxManage controlvm new-1-4-2 poweroff soft
VBoxManage controlvm new-2-4-2 poweroff soft
VBoxManage controlvm new-3-4-2 poweroff soft
VBoxManage controlvm new-4-4-2 poweroff soft
VBoxManage controlvm new-5-4-2 poweroff soft
